heat_template_version: 2015-10-15
description: Launch a basic instance with specified ubuntu image using the
             ``mininet`` flavor, ``mykey`` key,  and two networks private, net_mgmt.

parameters:
  NetID:
    type: string
    description: Network ID to use for the instance.
    default: private_s1
  NetID2:
    type: string
    description: 2nd Network ID to use for the instance
    default: net_mgmt
  NetID3:
    type: string
    description: 3rd Network ID to use for the instance
    default: private_s2
  NetID4:
    type: string
    description: 4th Network ID to use for the instance
    default: test_nw
  IMAGE1:
    type: string
    description: Image name
    default: host-ubuntu 


resources:
  server1:
    type: OS::Nova::Server
    properties:
      image: { get_param: IMAGE1 }
      flavor: 1gb
      key_name: key234demo
      networks:
      - network: { get_param: NetID }
      - network: { get_param: NetID4 }

  server2:
    type: OS::Nova::Server
    properties:
      image: { get_param: IMAGE1 }
      flavor: 1gb
      key_name: key234demo
      networks:
      - network: { get_param: NetID }
      - network: { get_param: NetID4 }

outputs:
  instance_name:
    description: Name of the instance.
    value: { get_attr: [ server1, name ] }
  instance_ip:
    description: IP address of the instance.
    value: { get_attr: [ server1, first_address ] }
  instance_name:
    description: Name of the instance.
    value: { get_attr: [ server2, name ] }
  instance_ip:
    description: IP address of the instance.
    value: { get_attr: [ server2, first_address ] }

